// +build !ignore_autogenerated

// Code generated by operator-sdk-v0.16.0-x86_64-apple-darwin. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeUtil) DeepCopyInto(out *KobeUtil) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeUtil.
func (in *KobeUtil) DeepCopy() *KobeUtil {
	if in == nil {
		return nil
	}
	out := new(KobeUtil)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KobeUtil) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeUtilList) DeepCopyInto(out *KobeUtilList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KobeUtil, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeUtilList.
func (in *KobeUtilList) DeepCopy() *KobeUtilList {
	if in == nil {
		return nil
	}
	out := new(KobeUtilList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KobeUtilList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeUtilSpec) DeepCopyInto(out *KobeUtilSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeUtilSpec.
func (in *KobeUtilSpec) DeepCopy() *KobeUtilSpec {
	if in == nil {
		return nil
	}
	out := new(KobeUtilSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeUtilStatus) DeepCopyInto(out *KobeUtilStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeUtilStatus.
func (in *KobeUtilStatus) DeepCopy() *KobeUtilStatus {
	if in == nil {
		return nil
	}
	out := new(KobeUtilStatus)
	in.DeepCopyInto(out)
	return out
}
