// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/kobeutil/v1alpha1.KobeUtil":       schema_pkg_apis_kobeutil_v1alpha1_KobeUtil(ref),
		"./pkg/apis/kobeutil/v1alpha1.KobeUtilSpec":   schema_pkg_apis_kobeutil_v1alpha1_KobeUtilSpec(ref),
		"./pkg/apis/kobeutil/v1alpha1.KobeUtilStatus": schema_pkg_apis_kobeutil_v1alpha1_KobeUtilStatus(ref),
	}
}

func schema_pkg_apis_kobeutil_v1alpha1_KobeUtil(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KobeUtil is the Schema for the kobeutils API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kobeutil/v1alpha1.KobeUtilSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kobeutil/v1alpha1.KobeUtilStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kobeutil/v1alpha1.KobeUtilSpec", "./pkg/apis/kobeutil/v1alpha1.KobeUtilStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kobeutil_v1alpha1_KobeUtilSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KobeUtilSpec defines the desired state of KobeUtil",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_kobeutil_v1alpha1_KobeUtilStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KobeUtilStatus defines the observed state of KobeUtil",
				Type:        []string{"object"},
			},
		},
	}
}
