site_name: KOBE Docs
site_url: https://semagrow.github.com/kobe/
repo_url: https://github.com/semagrow/kobe/
repo_name: 'GitHub'
docs_dir: 'docs'
nav:
  - 'Home': index.md
  - 'Walkthroughs': 
     - 'Benchmark': BenchmarkWalkthrough.md
     - 'DatasetTemplate': DatasetTemplateWalkthrough.md
     - 'Experiment': ExperimentWalkthrough.md
     - 'FederatorTemplate': FederatorTemplateWalkthrough.md

theme:
  name: readthedocs
