site_name: KOBE Open Benchmarking Engine
site_url: https://semagrow.github.com/kobe/
repo_url: https://github.com/semagrow/kobe/
repo_name: 'GitHub'
docs_dir: 'docs'
nav:
  - 'Home': index.md
  - 'Getting started':
     - 'Installation': getting_started/install.md
     - 'Perform a benchmark experiment': getting_started/run_experiment.md
     - 'Evaluate the results': getting_started/view_results.md
  - 'Using KOBE':
     - 'Create a new benchmark': use/create_benchmark.md
     - 'Tune network settings': use/tune_network.md
     - 'Create a new experiment': use/create_experiment.md
  - 'Extending KOBE':
     - 'Add a new federator': extend/add_federator.md
     - 'Provide metric support': extend/support_metrics.md
     - 'Add new metrics': extend/add_metrics.md
     - 'Add a new evaluator': extend/add_evaluator.md
     - 'Add a new dataset server': extend/add_dataset_server.md
  - 'References':
     - 'Components': references/components.md
     - 'API': references/api.md
     - 'Command line': references/kobectl.md

theme:
  name: material
  features:
    - navigation.tabs
    - search
    - header.autohide

markdown_extensions:
  - fenced_code
  - pymdownx.highlight
  - pymdownx.superfences


