site_name: KOBE Benchmark Engine
site_url: https://semagrow.github.com/kobe/
repo_url: https://github.com/semagrow/kobe/
repo_name: 'GitHub'
docs_dir: 'docs'
nav:
  - 'Home': index.md
  - 'Getting started':
     - 'Install': getting_started/install.md
     - 'Run': getting_started/run.md
  - 'Using KOBE':
     - 'Create a new experiment': use/experiment.md
     - 'Create a benchmark': use/benchmark.md 
  - 'Extending KOBE':
     - 'Create a data source': extend/datasettemplate.md
     - 'Create a federator': extend/federatortemplate.md
  - 'References':
     - 'API': api.md

theme:
  name: material
  features:
    - navigation.tabs
    - search
    - header.autohide

