apiVersion: kobe.semagrow.org/v1alpha1
kind: FederatorTemplate
metadata:
  name: semagrowtemplate-prefix
spec:
  containers:
    - name: maincontainer 
      image: semagrow/semagrow:gss
      ports:
      - containerPort: 8080
  port: 8080
  path: /SemaGrow/sparql
  confFromFileImage: alpine:3
  inputDumpDir: /semagrow/input
  outputDumpDir: /semagrow/output
  confImage: antru6/semagrow-init-prefix-19
  inputDir: /input
  outputDir: /output
  fedConfDir: /etc/default/semagrow
