apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobe-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kobe-operator
  template:
    metadata:
      labels:
        name: kobe-operator
    spec:
      serviceAccountName: kobe-operator
      containers:
        - name: operator
          # Replace this with the built image name
          image: semagrow/kobe-operator:3.0.3
          command:
          - operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kobe-operator"
