apiVersion: kobe.semagrow.org/v1alpha1
kind: Experiment
metadata:
  name: toyexp
spec:
  benchmark: toybench-simple
  federatorName: semagrow-toy-simple
  federatorTemplateRef: semagrowtemplate
  evaluator:
    image: semagrow/kobe-sequential-evaluator
  timesToRun: 3
  dryRun: false
  forceNewInit: true 
