apiVersion: kobe.semagrow.org/v1alpha1
kind: Experiment
metadata:
  name: gssbench-exp-prefix
spec:
  benchmark: gssbench
  federatorName: semagrow-prefix
  federatorTemplateRef: semagrowtemplate-prefix
  evaluator:
    image: semagrow/kobe-sequential-evaluator
    env:
     - name: TIMEOUT
       value: "300000"
  timesToRun: 3
  dryRun: false
  forceNewInit: false 

