apiVersion: kobe.semagrow.org/v1alpha1
kind: Experiment
metadata:
  name: gssbench-exp-basic
spec:
  benchmark: gssbench
  federatorName: semagrow-basic
  federatorTemplateRef: semagrowtemplate-basic
  evaluator:
    image: semagrow/kobe-sequential-evaluator
    env:
     - name: TIMEOUT
       value: "300000"
  timesToRun: 3
  dryRun: false
  forceNewInit: false 

