// +build !ignore_autogenerated

// Code generated by operator-sdk-v0.16.0-x86_64-apple-darwin. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fed) DeepCopyInto(out *Fed) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fed.
func (in *Fed) DeepCopy() *Fed {
	if in == nil {
		return nil
	}
	out := new(Fed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Federator) DeepCopyInto(out *Federator) {
	*out = *in
	in.Affinity.DeepCopyInto(&out.Affinity)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Federator.
func (in *Federator) DeepCopy() *Federator {
	if in == nil {
		return nil
	}
	out := new(Federator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeExperiment) DeepCopyInto(out *KobeExperiment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeExperiment.
func (in *KobeExperiment) DeepCopy() *KobeExperiment {
	if in == nil {
		return nil
	}
	out := new(KobeExperiment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KobeExperiment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeExperimentList) DeepCopyInto(out *KobeExperimentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KobeExperiment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeExperimentList.
func (in *KobeExperimentList) DeepCopy() *KobeExperimentList {
	if in == nil {
		return nil
	}
	out := new(KobeExperimentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KobeExperimentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeExperimentSpec) DeepCopyInto(out *KobeExperimentSpec) {
	*out = *in
	if in.EvalCommands != nil {
		in, out := &in.EvalCommands, &out.EvalCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeExperimentSpec.
func (in *KobeExperimentSpec) DeepCopy() *KobeExperimentSpec {
	if in == nil {
		return nil
	}
	out := new(KobeExperimentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KobeExperimentStatus) DeepCopyInto(out *KobeExperimentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KobeExperimentStatus.
func (in *KobeExperimentStatus) DeepCopy() *KobeExperimentStatus {
	if in == nil {
		return nil
	}
	out := new(KobeExperimentStatus)
	in.DeepCopyInto(out)
	return out
}
