// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/kobeexperiment/v1alpha1.Federator":            schema_pkg_apis_kobeexperiment_v1alpha1_Federator(ref),
		"./pkg/apis/kobeexperiment/v1alpha1.KobeExperiment":       schema_pkg_apis_kobeexperiment_v1alpha1_KobeExperiment(ref),
		"./pkg/apis/kobeexperiment/v1alpha1.KobeExperimentSpec":   schema_pkg_apis_kobeexperiment_v1alpha1_KobeExperimentSpec(ref),
		"./pkg/apis/kobeexperiment/v1alpha1.KobeExperimentStatus": schema_pkg_apis_kobeexperiment_v1alpha1_KobeExperimentStatus(ref),
	}
}

func schema_pkg_apis_kobeexperiment_v1alpha1_Federator(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Federator is helper struct",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"image": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"imagePullPolicy": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"affinity": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/api/core/v1.Affinity"),
						},
					},
					"port": {
						SchemaProps: spec.SchemaProps{
							Description: "choose which nodes the fed likes to run in",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"confFromFileImage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"inputFileDir": {
						SchemaProps: spec.SchemaProps{
							Description: "image that makes init file from dump or endpoint",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"outputFileDir": {
						SchemaProps: spec.SchemaProps{
							Description: "where the above image expects the dump to be(if from dump)",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"confImage": {
						SchemaProps: spec.SchemaProps{
							Description: "where the above image will place its result config file",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"name", "image", "imagePullPolicy", "affinity", "port", "confFromFileImage", "inputFileDir", "outputFileDir", "confImage"},
			},
		},
		Dependencies: []string{
			"k8s.io/api/core/v1.Affinity"},
	}
}

func schema_pkg_apis_kobeexperiment_v1alpha1_KobeExperiment(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KobeExperiment is the Schema for the kobeexperiments API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kobeexperiment/v1alpha1.KobeExperimentSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kobeexperiment/v1alpha1.KobeExperimentStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kobeexperiment/v1alpha1.KobeExperimentSpec", "./pkg/apis/kobeexperiment/v1alpha1.KobeExperimentStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kobeexperiment_v1alpha1_KobeExperimentSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KobeExperimentSpec defines the desired state of KobeExperiment",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"benchmark": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"federator": {
						SchemaProps: spec.SchemaProps{
							Description: "Federator    []Fed    `json:\"federator\"`",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"dryRun": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"timesToRun": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"forceNewInit": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"evalImage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"evalCommands": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"benchmark", "federator", "dryRun", "timesToRun", "forceNewInit", "evalImage", "evalCommands"},
			},
		},
	}
}

func schema_pkg_apis_kobeexperiment_v1alpha1_KobeExperimentStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KobeExperimentStatus defines the observed state of KobeExperiment",
				Type:        []string{"object"},
			},
		},
	}
}
